apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: iot-vs
  namespace: agrandfield
spec:
  host: virtual.localhost
  routes:
  - path: /agrandfield
    route: agrandfield/iot-vsr
  - path: /coffee
    route: coffee/coffeevirtual
