apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: iot-vsr 
  namespace: agrandfield
spec:
  host: virtual.localhost
  upstreams:
  - name: cloudvisuserver 
    service: cloudvisuserver
    port: 80
  subroutes:
  - path: /agrandfield/cloudvisuserver
    action:
      proxy:
        upstream: cloudvisuserver
        rewritePath: /cloudvisuserver

---

apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: coffeevirtual
  namespace: coffee
spec:
  host: virtual.localhost
  upstreams:
  - name: coffee 
    service: coffee-svc
    port: 80
  subroutes:
  - path: /coffee 
    action:
      pass: coffee