apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: tea 
  namespace: tea
  annotations:
    nginx.org/rewrites: "serviceName=devicesim rewrite=/;serviceName=cloudvisuserver rewrite=/cloudvisuserver"
spec:
  host: cafe.localhost
  upstreams:
  - name: tea 
    service: tea-svc
    port: 80
  subroutes:
  - path:  /tea
    action:
      pass: tea