apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: virtual-server
spec:
  host: virtual.localhost
  routes:
  - path: /.*
    route: ns1/virtual-route   #ns/vsr name

#  - path: ^/([a-zA-Z]+)/.*
#    route: $1/virtual-route   #ns/vsr name
